Repository NaverCloudPlatform/terraform-provider-ncloud, pull requests merged in 2021-03, with the labels that each got.

#153 change `access_control_groups` to required
  docs/resources/network_interface.md
  ncloud/resource_ncloud_network_interface.go
Labels: VPC, bug

#152 #151 Support vpc load balancer
  docs/data-sources/lb.md
  docs/data-sources/lb_listener.md
  docs/data-sources/lb_target_group.md
  docs/resources/lb.md
  docs/resources/lb_listener.md
  docs/resources/lb_target_group.md
  docs/resources/lb_target_group_attachment.md
  go.mod
  go.sum
  ncloud/common.go
  ncloud/config.go
  ncloud/data_source_ncloud_lb.go
  ncloud/data_source_ncloud_lb_listener.go
  ncloud/data_source_ncloud_lb_listener_test.go
  ncloud/data_source_ncloud_lb_target_group.go
  ncloud/data_source_ncloud_lb_target_group_test.go
  ncloud/data_source_ncloud_lb_test.go
  ncloud/helpers.go
  ncloud/resource_ncloud_lb.go
  ncloud/resource_ncloud_lb_listener.go
  ncloud/resource_ncloud_lb_listener_test.go
  ncloud/resource_ncloud_lb_target_group.go
  ncloud/resource_ncloud_lb_target_group_attachment.go
  ncloud/resource_ncloud_lb_target_group_attachment_test.go
  ncloud/resource_ncloud_lb_target_group_test.go
  ncloud/resource_ncloud_lb_test.go
  ncloud/types.go
Labels: VPC, documentation, new-data-source, new-resource

#154 Add ForceNew in auto scaling and modify docs
  docs/data-sources/auto_scaling_group.md
  docs/data-sources/auto_scaling_policy.md
  docs/data-sources/launch_configuration.md
  docs/resources/auto_scaling_group.md
  docs/resources/auto_scaling_schedule.md
  docs/resources/auto_sclaing_policy.md
  docs/resources/launch_configuration.md
  ncloud/resource_ncloud_auto_scaling_group.go
  ncloud/resource_ncloud_auto_scaling_policy.go
  ncloud/resource_ncloud_auto_scaling_schedule.go
  ncloud/resource_ncloud_launch_configuration.go
Labels: documentation
