Repository NaverCloudPlatform/terraform-provider-ncloud, pull requests merged in 2024-04, with the labels that each got.

#421 fix(MongoDb): Update errors and doc typo
  docs/data-sources/mongodb_image_products.md
  internal/common/convert_types.go
  internal/service/mongodb/mongodb.go
Labels: bug, documentation, VPC, FRAMEWORK

#419 feat(nks): nks_versions_data_source hypervisor_code
  docs/data-sources/nks_cluster.md
  docs/data-sources/nks_versions.md
  docs/resources/nks_cluster.md
  go.mod
  go.sum
  internal/service/nks/nks_versions_data_source.go
  internal/service/nks/nks_versions_data_source_test.go
Labels: enhancement, documentation, VPC, SDKv2

#420 refactor(hadoop): Update Hadoop resource and datasource
  docs/data-sources/hadoop.md
  docs/resources/hadoop.md
  examples/hadoop/main.tf
  examples/hadoop/variables.tf
  internal/service/hadoop/hadoop.go
  internal/service/hadoop/hadoop_data_source.go
  internal/service/hadoop/hadoop_data_source_test.go
  internal/service/hadoop/hadoop_test.go
Labels: enhancement, documentation, VPC, FRAMEWORK
