Repository NaverCloudPlatform/terraform-provider-ncloud, pull requests merged in 2024-12, with the labels that each got.

#492 feat(vpc_lb): Add UDP to protocol
  docs/resources/lb_listener.md
  docs/resources/lb_target_group.md
  internal/service/loadbalancer/lb_listener.go
  internal/service/loadbalancer/lb_target_group.go
Labels: enhancement, documentation, VPC, SDKv2

#489 fix(mysql): Fix import error and minor errors on recovery and slave
  docs/resources/mysql_recovery.md
  docs/resources/mysql_slave.md
  internal/service/mysql/mysql.go
  internal/service/mysql/mysql_data_source.go
  internal/service/mysql/mysql_recovery.go
  internal/service/mysql/mysql_recovery_test.go
  internal/service/mysql/mysql_slave.go
  internal/service/mysql/mysql_slave_test.go
  internal/service/mysql/mysql_test.go
Labels: bug, documentation, VPC, FRAMEWORK

#490 feat(vpc_lb): Add XLARGE to the throughput_type
  docs/resources/lb.md
  internal/service/loadbalancer/lb.go
Labels: enhancement, documentation, VPC, FRAMEWORK

#495 fix(mysql_databases): Fix datasource typo
  docs/data-sources/mysql_databases.md
Labels: documentation

#496 fix(mysql_databases): Fix resource doc
  docs/resources/mysql_databases.md
Labels: documentation

#493 fix: Deprecate `ncloud_load_balancer_ssl_certificate` resource
  docs/resources/load_balancer_ssl_certificate.md
  internal/service/classicloadbalancer/load_balancer_ssl_certificate.go
  internal/service/classicloadbalancer/load_balancer_ssl_certificate_test.go
Labels: documentation, Classic, SDKv2

#498 fix(mysql_databases): Fix minor errors
  internal/service/mysql/mysql_databases.go
  internal/service/mysql/mysql_databases_data_source.go
Labels: VPC, FRAMEWORK

#494 docs(Terraform remote state): Add documentation of remote state
  docs/guides/Configure Remote State Backend for Ncloud.md
Labels: documentation

#491 fix(objectstorage): Fix obs import error
  docs/resources/objectstorage_bucket.md
  docs/resources/objectstorage_bucket_acl.md
  docs/resources/objectstorage_object.md
  docs/resources/objectstorage_object_acl.md
  docs/resources/objectstorage_object_copy.md
  internal/service/objectstorage/objectstorage_bucket.go
  internal/service/objectstorage/objectstorage_bucket_acl.go
  internal/service/objectstorage/objectstorage_bucket_acl_test.go
  internal/service/objectstorage/objectstorage_bucket_test.go
  internal/service/objectstorage/objectstorage_object.go
  internal/service/objectstorage/objectstorage_object_acl.go
  internal/service/objectstorage/objectstorage_object_acl_test.go
  internal/service/objectstorage/objectstorage_object_copy.go
  internal/service/objectstorage/objectstorage_object_copy_test.go
  internal/service/objectstorage/objectstorage_object_data_source.go
  internal/service/objectstorage/objectstorage_object_test.go
Labels: bug, documentation, FRAMEWORK

#505 test: Change the ACC test code to deprecate CentOS images
  internal/service/autoscaling/auto_scaling_adjustment_types_data_source_test.go
  internal/service/autoscaling/auto_scaling_group_data_source_test.go
  internal/service/autoscaling/auto_scaling_group_test.go
  internal/service/autoscaling/auto_scaling_policy_data_source_test.go
  internal/service/autoscaling/auto_scaling_policy_test.go
  internal/service/autoscaling/auto_scaling_schedule_data_source_test.go
  internal/service/autoscaling/auto_scaling_schedule_test.go
  internal/service/autoscaling/launch_configuration_data_source_test.go
  internal/service/autoscaling/launch_configuration_test.go
  internal/service/devtools/sourcedeploy_project_stage_data_source_test.go
  internal/service/devtools/sourcedeploy_project_stage_scenarios_data_source_test.go
  internal/service/loadbalancer/lb_target_group_attachment_test.go
  internal/service/mongodb/mongodb_products_data_source_test.go
  internal/service/mysql/mysql_products_data_source_test.go
  internal/service/nasvolume/nas_volume_test.go
  internal/service/redis/redis_data_source_test.go
  internal/service/redis/redis_products_data_source_test.go
  internal/service/server/block_storage_test.go
  internal/service/server/network_interface_test.go
  internal/service/server/port_forwarding_rule_test.go
  internal/service/server/public_ip_data_source_test.go
  internal/service/server/public_ip_test.go
  internal/service/server/root_password_data_source_test.go
  internal/service/server/server_data_source_test.go
  internal/service/server/server_image_data_source_test.go
  internal/service/server/server_product_data_source_test.go
  internal/service/server/server_products_data_source_test.go
  internal/service/server/server_test.go
  internal/service/server/servers_data_source_test.go
Labels: regression, VPC, Classic

#506 doc: Modify documentation due to end of centOS sales
  docs/data-sources/auto_scaling_adjustment_types.md
  docs/data-sources/cdss_os_image.md
  docs/data-sources/hadoop_add_on.md
  docs/data-sources/hadoop_image_products.md
  docs/data-sources/hadoop_products.md
  docs/data-sources/server_image.md
  docs/data-sources/server_images.md
  docs/data-sources/server_product.md
  docs/data-sources/server_products.md
  docs/data-sources/ses_node_os_images.md
  docs/resources/auto_scaling_group.md
  docs/resources/auto_scaling_policy.md
  docs/resources/auto_scaling_schedule.md
  docs/resources/init_script.md
  docs/resources/launch_configuration.md
  docs/resources/placement_group.md
  docs/resources/server.md
Labels: documentation
