Repository NaverCloudPlatform/terraform-provider-ncloud, pull requests merged in 2024-02, with the labels that each got.

#390 feat: Add hadoop resource and data source (#370)
  docs/data-sources/hadoop.md
  docs/data-sources/hadoop_add_on.md
  docs/data-sources/hadoop_bucket.md
  docs/data-sources/hadoop_image.md
  docs/data-sources/hadoop_images.md
  docs/data-sources/hadoops.md
  docs/resources/hadoop.md
  examples/hadoop/main.tf
  examples/hadoop/variables.tf
  examples/hadoop/versions.tf
  examples/hadoop_add_on/main.tf
  examples/hadoop_add_on/variables.tf
  examples/hadoop_add_on/versions.tf
  examples/hadoop_buckets/main.tf
  examples/hadoop_buckets/variables.tf
  examples/hadoop_buckets/versions.tf
  examples/hadoop_images/main.tf
  examples/hadoop_images/variables.tf
  examples/hadoop_images/versions.tf
  internal/conn/config.go
  internal/provider/fwprovider/provider.go
  internal/service/hadoop/hadoop.go
  internal/service/hadoop/hadoop_add_on_data_source.go
  internal/service/hadoop/hadoop_add_on_data_source_test.go
  internal/service/hadoop/hadoop_bucket_data_source.go
  internal/service/hadoop/hadoop_bucket_data_source_test.go
  internal/service/hadoop/hadoop_data_source.go
  internal/service/hadoop/hadoop_data_source_test.go
  internal/service/hadoop/hadoop_images_data_source.go
  internal/service/hadoop/hadoop_images_data_source_test.go
  internal/service/hadoop/hadoop_test.go
  internal/service/hadoop/hadoops_data_source.go
  internal/service/hadoop/hadoops_data_source_test.go
Labels: new-data-source, new-resource, VPC, FRAMEWORK

#410 refactor: remove Hadoop docs and datasources
  docs/data-sources/hadoop_image.md
  docs/data-sources/hadoops.md
  internal/provider/fwprovider/provider.go
  internal/service/hadoop/hadoops_data_source.go
  internal/service/hadoop/hadoops_data_source_test.go
Labels: documentation, VPC, FRAMEWORK

#411 refactor(hadoop): Update Hadoop image products Data Source
  docs/data-sources/hadoop_image_products.md
  docs/data-sources/hadoop_images.md
  examples/hadoop_images/main.tf
  examples/hadoop_images/variables.tf
  examples/hadoop_images/versions.tf
  internal/common/data_source.go
  internal/provider/fwprovider/provider.go
  internal/service/hadoop/hadoop_image_products_data_source.go
  internal/service/hadoop/hadoop_image_products_data_source_test.go
  internal/service/hadoop/hadoop_images_data_source.go
  internal/service/hadoop/hadoop_images_data_source_test.go
Labels: enhancement, documentation, VPC, FRAMEWORK

#412 fix(redis): Apply omitempty to user_name and user_password
  go.mod
  go.sum
Labels: VPC, FRAMEWORK

#413 feat(hadoop): Add hadoop products data source
  docs/data-sources/hadoop_products.md
  internal/provider/fwprovider/provider.go
  internal/service/hadoop/hadoop_products_data_source.go
  internal/service/hadoop/hadoop_products_data_source_test.go
Labels: new-data-source, documentation, VPC, FRAMEWORK
